[package]
name = "tephra"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
winit = "0.21"
nalgebra-glm = "0.7.0"

[lib]
name = "support"
path = "src/support/lib.rs"
